export const qk = {
  me: ['me'] as const,
  users: ['users'] as const,
  user: (id: string) => ['users', id] as const,
  classes: ['classes'] as const,
  class: (id: string) => ['classes', id] as const,
  classStudents: (id: string) => ['classes', id, 'students'] as const,
  classAdmins: (id: string) => ['classes', id, 'admins'] as const,
  lessons: (classId: string) => ['classes', classId, 'lessons'] as const,
  lesson: (id: string) => ['lessons', id] as const,
  materials: (classId: string) => ['classes', classId, 'materials'] as const,
  material: (id: string) => ['materials', id] as const,
  assignments: (classId?: string) => classId ? ['classes', classId, 'assignments'] : ['assignments'] as const,
  assignment: (id: string) => ['assignments', id] as const,
  submissions: (assignmentId: string) => ['assignments', assignmentId, 'submissions'] as const,
  submission: (id: string) => ['submissions', id] as const,
  mySubmissions: ['me', 'submissions'] as const,
  gradingQueue: (classId: string) => ['classes', classId, 'grading'] as const,
  notifications: ['notifications'] as const,
} as const
